version: '3.9'
services:
  pedion-ecommerce:
    container_name: pedion-ecommerce
    build:
      context: .
    ports:
      - 443:3000
    restart: always
    networks:
      - www

networks:
  www:
    name: www
